version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'dbadmin'
      MYSQL_PASSWORD: 'dev12345'
      MYSQL_ROOT_PASSWORD: 'dev12345'

    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: