- name: Configure instance
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Update system
      yum:
        name: '*'
        state: latest
        update_only: true

    - name: "Make sure boto is installed"
      pip:
        name: ['docker', 'boto3']

    - name: Install Docker
      yum:
        state: latest
        name: docker

    - name: Start docker
      service:
        name: docker
        enabled:  true
        state:  started

    - name: Add user to docker group
      user:
        name: ec2-user
        append: yes
        groups:  docker

    - name: Create directory for the whole project solution
      file:
        path: /App
        state: directory


    - name: Create directory for the Core project source
      file:
        path: /App/Core
        state: directory

    - name: Create directory for the UserService source
      file:
        path: /App/UserService
        state:  directory

    - name: Copy Core Project files to destination
      synchronize:
        src: ../../Core/
        dest: /App/Core
        owner: yes

    - name: Copy UserService files to destination
      synchronize:
        src:  ../../UserService/
        dest: /App/UserService
        owner: yes

    - name: Build the docker image
      docker_image:
        name: user-service
        tag: v1
        source: build
        build:
          dockerfile: /App/UserService/Deployment/Dockerfile
          path: /App
        state: present

    - name: Start the container in port
      docker_container:
        name: user-service
        state: started
        image: user-service:v1
        published_ports: ['6000:6000']
        restart_policy: always